"""add measurements table

Revision ID: 45fde3a116eb
Revises: c0b7e6dffad9
Create Date: 2026-09-14 07:57:18.804241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "45fde3a116eb"
down_revision: Union[str, None] = "c0b7e6dffad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("analysis_job_id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "measurement_type",
            sa.Enum(
                "point_elevation", "distance", "profile", "coordinate", name="measurement_type"
            ),
            nullable=False,
        ),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["artifact_id"], ["analysis_artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurements_analysis_job_id"), "measurements", ["analysis_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_artifact_id"), "measurements", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_created_at"), "measurements", ["created_at"], unique=False
    )
    op.create_index(
        "ix_measurements_project_created",
        "measurements",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_project_id"), "measurements", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_measurements_user_id"), "measurements", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_measurements_user_id"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_project_id"), table_name="measurements")
    op.drop_index("ix_measurements_project_created", table_name="measurements")
    op.drop_index(op.f("ix_measurements_created_at"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_artifact_id"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_analysis_job_id"), table_name="measurements")
    op.drop_table("measurements")
    # Autogenerate does not drop the enum type it created for
    # 'measurement_type'; do it explicitly so a downgrade followed by a
    # re-upgrade doesn't hit "type measurement_type already exists" (same
    # pattern as 4d5fb992ace1_add_datasets_table.py).
    sa.Enum(name="measurement_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
