"""add calibration support

Revision ID: 51487b58569d
Revises: 9af84d3fba2a
Create Date: 2026-09-14 02:06:30.812092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '51487b58569d'
down_revision: Union[str, None] = '9af84d3fba2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Unlike op.create_table, op.add_column on an *existing* table does not
    # auto-create a brand-new enum type for you — it must exist first.
    sa.Enum(
        'uncalibrated', 'calibrating', 'calibrated', 'failed', name='calibration_status'
    ).create(op.get_bind(), checkfirst=True)
    sa.Enum(
        'source_image', 'dem_reference', 'gcp_reference', name='dataset_role'
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('calibration_status', sa.Enum('uncalibrated', 'calibrating', 'calibrated', 'failed', name='calibration_status'), server_default='uncalibrated', nullable=False))
    op.add_column('analysis_jobs', sa.Column('calibration_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('datasets', sa.Column('role', sa.Enum('source_image', 'dem_reference', 'gcp_reference', name='dataset_role'), server_default='source_image', nullable=False))
    op.add_column('datasets', sa.Column('gcp_crs', sa.String(length=255), nullable=True))
    op.add_column('datasets', sa.Column('gcp_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    # Hand-written: autogenerate does not diff native Postgres enum member
    # lists (see docs/DEVELOPMENT.md). New AnalysisStage values for the
    # Phase 4 calibration pipeline, inserted in pipeline order between
    # 'writing_depth' and the legacy 'executing' value.
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'calibrating' AFTER 'writing_depth'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'writing_metric_elevation' AFTER 'calibrating'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'writing_dsm' AFTER 'writing_metric_elevation'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'validating_results' AFTER 'writing_dsm'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'gcp_points')
    op.drop_column('datasets', 'gcp_crs')
    op.drop_column('datasets', 'role')
    op.drop_column('analysis_jobs', 'calibration_metadata')
    op.drop_column('analysis_jobs', 'calibration_status')
    # ### end Alembic commands ###

    # Autogenerate does not drop the enum types it created for these
    # columns; do it explicitly so a downgrade followed by a re-upgrade
    # doesn't hit "type already exists".
    sa.Enum(name='dataset_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='calibration_status').drop(op.get_bind(), checkfirst=True)
    # The four new analysis_stage values added above cannot be removed
    # (Postgres has no DROP VALUE for enums) — see this migration's upgrade()
    # and docs/DEVELOPMENT.md. A downgrade that ran upgrade()'s ALTER TYPE
    # statements cannot be fully reversed.
