"""add reports table

Revision ID: a0d3ac929883
Revises: a4f198e31d97
Create Date: 2026-09-14 12:29:17.752933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a0d3ac929883"
down_revision: Union[str, None] = "a4f198e31d97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "generating", "completed", "failed", name="report_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("report_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pdf_storage_key", sa.String(length=500), nullable=True),
        sa.Column("csv_storage_key", sa.String(length=500), nullable=True),
        sa.Column("bundle_storage_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_index(op.f("ix_reports_dataset_id"), "reports", ["dataset_id"], unique=False)
    op.create_index(
        "ix_reports_project_created", "reports", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False)
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_index("ix_reports_project_created", table_name="reports")
    op.drop_index(op.f("ix_reports_dataset_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
    # Autogenerate does not drop the enum type it created for 'report_status';
    # do it explicitly so a downgrade followed by a re-upgrade doesn't hit
    # "type report_status already exists" (same pattern as
    # 4d5fb992ace1_add_datasets_table.py / 45fde3a116eb_add_measurements_table.py).
    sa.Enum(name="report_status").drop(op.get_bind(), checkfirst=True)
