"""add disaster screening support

Revision ID: a4f198e31d97
Revises: 45fde3a116eb
Create Date: 2026-09-14 11:10:48.402950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a4f198e31d97"
down_revision: Union[str, None] = "45fde3a116eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Unlike op.create_table, op.add_column on an *existing* table does not
    # auto-create a brand-new enum type for you — it must exist first (see
    # the calibration_status/semantic_status precedent in 51487b58569d /
    # c0b7e6dffad9).
    sa.Enum("not_requested", "processing", "completed", "failed", name="disaster_status").create(
        op.get_bind(), checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_jobs",
        sa.Column(
            "disaster_status",
            sa.Enum("not_requested", "processing", "completed", "failed", name="disaster_status"),
            server_default="not_requested",
            nullable=False,
        ),
    )
    op.add_column(
        "analysis_jobs",
        sa.Column("disaster_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    # Hand-written: autogenerate does not diff native Postgres enum member
    # lists (see docs/DEVELOPMENT.md). New AnalysisStage values for the
    # Phase 8 disaster-screening pipeline, inserted in enum-declaration
    # order between 'writing_semantic' (Phase 6's last stage) and the
    # legacy 'executing' value.
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'loading_terrain_data' AFTER 'writing_semantic'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'computing_slope' AFTER 'loading_terrain_data'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'computing_aspect' AFTER 'computing_slope'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'computing_terrain_statistics' AFTER 'computing_aspect'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'running_flood_screening' AFTER 'computing_terrain_statistics'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'running_landslide_screening' AFTER 'running_flood_screening'"
    )
    op.execute(
        "ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'writing_hazard_artifacts' AFTER 'running_landslide_screening'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "disaster_metadata")
    op.drop_column("analysis_jobs", "disaster_status")
    # ### end Alembic commands ###

    # Autogenerate does not drop the enum type it created for this column;
    # do it explicitly so a downgrade followed by a re-upgrade doesn't hit
    # "type already exists".
    sa.Enum(name="disaster_status").drop(op.get_bind(), checkfirst=True)
    # The seven new analysis_stage values added above cannot be removed
    # (Postgres has no DROP VALUE for enums) — see this migration's upgrade()
    # and docs/DEVELOPMENT.md. A downgrade that ran upgrade()'s ALTER TYPE
    # statements cannot be fully reversed.
