"""add analysis jobs and artifacts

Revision ID: a883d44def98
Revises: 4d5fb992ace1
Create Date: 2026-09-13 17:37:13.999660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a883d44def98'
down_revision: Union[str, None] = '4d5fb992ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='analysis_job_status'), server_default='queued', nullable=False),
    sa.Column('current_stage', sa.Enum('queued', 'preparing', 'validating_input', 'executing', 'finalizing', 'completed', name='analysis_stage'), server_default='queued', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_created_at'), 'analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_dataset_id'), 'analysis_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_project_id'), 'analysis_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.create_index('ux_analysis_jobs_active_dataset', 'analysis_jobs', ['dataset_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('analysis_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('artifact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_artifacts_analysis_job_id'), 'analysis_artifacts', ['analysis_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_artifacts_analysis_job_id'), table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    op.drop_index('ux_analysis_jobs_active_dataset', table_name='analysis_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_project_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_dataset_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_created_at'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # Autogenerate does not drop the enum types it created; do it explicitly
    # so a downgrade followed by a re-upgrade doesn't hit "type already exists".
    sa.Enum(name='analysis_stage').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analysis_job_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
