"""add semantic segmentation support

Revision ID: c0b7e6dffad9
Revises: 51487b58569d
Create Date: 2026-09-14 06:18:53.507965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c0b7e6dffad9'
down_revision: Union[str, None] = '51487b58569d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Unlike op.create_table, op.add_column on an *existing* table does not
    # auto-create a brand-new enum type for you — it must exist first (see
    # the calibration_status/dataset_role precedent in 51487b58569d).
    sa.Enum(
        'not_requested', 'processing', 'completed', 'failed', name='semantic_status'
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('semantic_status', sa.Enum('not_requested', 'processing', 'completed', 'failed', name='semantic_status'), server_default='not_requested', nullable=False))
    op.add_column('analysis_jobs', sa.Column('semantic_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    # Hand-written: autogenerate does not diff native Postgres enum member
    # lists (see docs/DEVELOPMENT.md). New AnalysisStage values for the
    # Phase 6 semantic-segmentation pipeline, inserted in pipeline order
    # between 'validating_results' (Phase 4's last stage) and the legacy
    # 'executing' value.
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'loading_semantic_model' AFTER 'validating_results'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'semantic_preprocessing' AFTER 'loading_semantic_model'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'semantic_inference' AFTER 'semantic_preprocessing'")
    op.execute("ALTER TYPE analysis_stage ADD VALUE IF NOT EXISTS 'writing_semantic' AFTER 'semantic_inference'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'semantic_metadata')
    op.drop_column('analysis_jobs', 'semantic_status')
    # ### end Alembic commands ###

    # Autogenerate does not drop the enum type it created for this column;
    # do it explicitly so a downgrade followed by a re-upgrade doesn't hit
    # "type already exists".
    sa.Enum(name='semantic_status').drop(op.get_bind(), checkfirst=True)
    # The four new analysis_stage values added above cannot be removed
    # (Postgres has no DROP VALUE for enums) — see this migration's upgrade()
    # and docs/DEVELOPMENT.md. A downgrade that ran upgrade()'s ALTER TYPE
    # statements cannot be fully reversed.
